---
apiVersion: v1
kind: Service
metadata:
  name: private-node
  namespace: {{ .Release.Namespace }}
  labels:
    app: private-node
spec:
  ports:
  - port: 9933
    name: rpc
  - port: 9615
    name: metrics
  - port: {{ .Values.p2p_port }}
    targetPort: {{ .Values.p2p_ip }}
    name: p2p-port
  selector:
    app: polkadot-node
  type: LoadBalancer
